/* Update PHENOMINER_TERM_UNIT_SCALES with PHENOMINER_STANDARD_UNITS */
update PHENOMINER_TERM_UNIT_SCALES tus
set (tus.UNIT_TO)= (
select us.STANDARD_UNIT from PHENOMINER_STANDARD_UNITS us
where us.ONT_ID=tus.ONT_ID
) 
where (tus.ONT_ID) in
(select us.ONT_ID from PHENOMINER_STANDARD_UNITS us);

/* add to PHENOMINER_TERM_UNIT_SCALES for new records in PHENOMINER_UNIT_SCALES */
INSERT INTO PHENOMINER_TERM_UNIT_SCALES
SELECT UNIQUE CM.CLINICAL_MEASUREMENT_ONT_ID,
ER.MEASUREMENT_UNITS,SU.STANDARD_UNIT, 
US.SCALE, US.ZERO_OFFSET
FROM EXPERIMENT_RECORD ER, CLINICAL_MEASUREMENT CM,
PHENOMINER_STANDARD_UNITS SU, PHENOMINER_UNIT_SCALES US
WHERE ER.CLINICAL_MEASUREMENT_ID = CM.CLINICAL_MEASUREMENT_ID AND
CM.CLINICAL_MEASUREMENT_ONT_ID = SU.ONT_ID AND
ER.MEASUREMENT_UNITS = US.UNIT_FROM AND
SU.STANDARD_UNIT = US.UNIT_TO and
(ER.MEASUREMENT_UNITS,SU.STANDARD_UNIT ) not in (
select unit_from, unit_to from phenominer_term_unit_scales tus1 where tus1.ont_id=su.ont_id);

